version: "3.3"
services:
  app:
    container_name: "api-auth"
    build: .
    volumes:
      - .:/go/src/app
    environment:
      DB_URL: db:27017
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:3.2.21-jessie
    container_name: "mongo"
    restart: always
    ports:
      - "27100:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123456
